#  POST  http://localhost:5000/api/hostels/search
#  Content-Type: application/json

# {
#     "locality": "Bamunimoidam"
# }

# POST http://localhost:5000/api/pgs/filter?location=Dibrugarh, Assam, India
# Content-Type: application/json

# {
#     "max": 8000
# }


POST http://localhost:5000/api/add/pg
Content-Type: application/json

{
    "name": "Manab and his wife's PG",
    "location": "Bamunimaidan, Guwahati, Assam, India"
}