 
# POST  http://localhost:3000/api/update/hostels/6012d4f6cb2e1553983209ce
# Content-Type: application/json

# {
#     "cityName": "Dibrugarh",
#     "feature_image": "https://firebasestorage.googleapis.com/v0/b/fb-express-d6a56.appspot.com/o/images%2Fme.jpg?alt=media&token=2337c3ea-6a1f-4564-8799-bb94f284657a"
# }

# POST  http://localhost:5000/api/add/city
# Content-Type: application/json

# {
#     "cityName": "Dibrugarh"
# }

# POST http://localhost:5000/api/add/pg
# Content-Type: application/json

# {
#     "name": "Manab and his wife's PG",
#     "location": "Dibrugarh University, Dibrugarh, Assam, India"
# }

# GET http://localhost:5000/api/pgs/search?location=Dibrugarh, Assam, India


# USER SIGN IN
#  POST  http://localhost:5000/api/signin
# Content-Type: application/json

# {
#     "phone": "9365698129"
# }

#  POST  http://localhost:5000/api/verifyOTP
# Content-Type: application/json

# {
#     "phone": "9365698129",
#     "code": "341812"
# }